### ISSUE TITLE
Message payload might not be a JSON object

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/docgen#12]
We're currently documenting message payloads as if they're always JSON objects, but the reality is that it can be something else, for instance, a number. Here's an example:

https://ubidots.com/docs/api/mqtt.html#subscribe-to-a-variable

It says:

> `/v1.6/devices/{LABEL_DEVICE}/{LABEL_VARIABLE}/lv`: This will return the last value of the variable as a single float value. This makes it easier to parse in microcontrollers.

That's especially important for IoT devices.

**Comment by NicoHood** [comment]
```yaml
topics:
  accounts.1.0.action.user.signup:
    publish:
      $ref: "#/components/messages/userSignUp"
  accounts.1.0.event.user.signup:
    publish:
      payload:
        type: "string"
        description: "Simple response string"
        default: "test"
```
![image](https://user-images.githubusercontent.com/6888294/42894969-a38dd3c8-8ab8-11e8-9d4e-4d3c392bb7a3.png)

Seems to work for me already!?

**Comment by fmvilas** [comment]
Yes. I forgot to close this issue. Thanks!
