### ISSUE TITLE
Generate sample JSON for payload

### ISSUE THREAD

**Issue by lyubenivanov** [asyncapi/docgen#15]
It would be nice if the docgen can automatically generate JSON/XML sample for the payload. Similar to what widdershins + slate does.

**Comment by fmvilas** [comment]
Makes total sense. I like the idea.

**Comment by MikeRalphson** [comment]
The clever bit is done by https://github.com/APIs-guru/openapi-sampler

**Comment by fmvilas** [comment]
Interesting. Thanks @MikeRalphson.

**Comment by fmvilas** [comment]
@lyubenivanov this feature is now released and on npm under version 1.9.0.
