### ISSUE TITLE
Undefined parts in topic headlines

### ISSUE THREAD

**Issue by cajus** [asyncapi/docgen#18]
Opening the [online editor](http://editor.asyncapi.org/) generates HTML output with topics assembled fro m different parts, where some of the parts seem to be *undefined*:

`hitchundefinedaccountsundefined1undefined0undefinedactionundefineduserundefinedsignup`
 
The same can be reproduced running `adg` locally.

**Comment by fmvilas** [comment]
Thank you very much for reporting it @cajus. It's fixed now. Sorry for the inconveniences.

**Comment by cajus** [comment]
No problem at all. Thanks for your work on it @fmvilas!
