### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/docgen#3]
There is no LICENSE file, and neither README.md or package.json mention how the code is licensed. May also be worth noting that a version of Node.js with async/await support (v8.x.x+ I think) is required.

**Comment by fmvilas** [comment]
You're right. Gonna fix it now. Thanks for the reminder mate!

**Comment by fmvilas** [comment]
I think it's now fixed. I'm closing the issue. Thanks 👍
