### ISSUE TITLE
x-topic-separator only replaces first dot

### ISSUE THREAD

**Issue by NicoHood** [asyncapi/docgen#30]
Using the online editor with the option I get the following result:
![image](https://user-images.githubusercontent.com/6888294/42895443-3e986cec-8aba-11e8-93c5-7964b01863b7.png)

It might be a problem of the online editor, I did not try this tool from git sources.

**Comment by fmvilas** [comment]
It's correct. Just don't use dots in the topic name. The dots in the topic have no special meaning.

**Comment by NicoHood** [comment]
Please what? You mean I should use slashes directly? But what is this open then used for? I dont understand :S

**Comment by fmvilas** [comment]
Dots notation is for AMQP topics. If you're using MQTT just go straight for `accounts/1/event/user/signup` and tell AsyncAPI docgen your separator is a slash.
