### ISSUE TITLE
Fail to parse YAML content in latest version

### ISSUE THREAD

**Issue by mikekekekeke** [asyncapi/docgen#33]
I'm getting the same error like in [same issue](https://github.com/asyncapi/docgen/issues/29), but with latest version "asyncapi-docgen": "^1.10.3". Please help.

**Comment by fmvilas** [comment]
Looking into it. Thanks for reporting!

**Comment by fmvilas** [comment]
Hey @mikekekekeke. I just released a new version of the package with the examples on the README fixed. Check it out: https://github.com/asyncapi/docgen#as-a-module-in-your-project.

**Comment by mikekekekeke** [comment]
It working now. Thanks. @fmvilas
