### ISSUE TITLE
Supporting templates

### ISSUE THREAD

**Issue by m-mohr** [asyncapi/docgen#40]
Great tool, very useful. It would be great to make it easily possible to use template. For example, I'd like to have all my generated documentation to have a common header so that users can navigate between the different pages, but I don't see such an option here whereas ReDoc and other tools allow it. I don't really want to fork the whole repository, but simply use it with the cli and npm tools.

**Comment by fmvilas** [comment]
Hey @m-mohr! Check out https://github.com/asyncapi/generator. It has what you need. Hope it helps!

**Comment by m-mohr** [comment]
Thanks, great! Why is it not mentioned here? https://www.asyncapi.com/v1/tooling/docgens.html

**Comment by fmvilas** [comment]
Sorry, lately I don't have so much time. I should also be deprecating docgen and node-codegen soon.
