### ISSUE TITLE
"Topics" block remains displayed even when not used

### ISSUE THREAD

**Issue by ppseprus** [asyncapi/docgen#42]
Based on the AsyncAPI specs, the _topics_ property is optional as long as _stream_ or _events_ is used instead.

**YAML to Reproduce**
```yaml
asyncapi: "1.2.0"
info:
  title: AsyncAPI Sample
  version: 1.0.0

servers:
  - url: domain:1234
    scheme: ws

events:
  send:
    - $ref: '#/components/messages/sendMessage'
  receive:
    - $ref: '#/components/messages/receiveMessage'

components:
  messages:

    sendMessage:
      payload:
        type: object
        properties:
          abcd:
            type: string

    receiveMessage:
      payload:
        type: object
        properties:
          efgh:
            type: string
```

**Current Behaviour:**
The "Topics" is displayed, even though, it is not used.
![image](https://user-images.githubusercontent.com/1323285/54818476-a85ec080-4c99-11e9-89e4-b68a37d54c93.png)

**Expected Behaviour:**
The "Topics" block is not rendered.

**Comment by fmvilas** [comment]
Hey @ppseprus! 2 things:

1. Don't use this package as it's deprecated in favor of github.com/asyncapi/generator.
2. With the generator, you should be able to do: `ag asyncapi.yaml html`. However, you'll still have the same problem because this block is not conditionally rendered. Would you mind submitting a small PR to fix it? Here's an example where we did it for the Markdown generator: https://github.com/asyncapi/generator/blob/master/templates/markdown/.partials/content.md.

Thanks!

**Comment by MikeRalphson** [comment]
@fmvilas I think the github description and `README` should probably be changed to make it much clearer that this project is deprecated. Once outstanding issues are closed or moved, maybe even archive it?

**Comment by fmvilas** [comment]
Yes, agree. Can you help with this? I have a bunch of issues/tasks piling up 😅

**Comment by ppseprus** [comment]
Noted! Thanks! Will open a PR in a bit..

**Comment by MikeRalphson** [comment]
@fmvilas yep - no problem.

**Comment by fmvilas** [comment]
Thanks folks!

**Comment by MikeRalphson** [comment]
@fmvilas could you give me / the core-team access to this repo too, so I can amend the description?

**Comment by fmvilas** [comment]
I thought you had access to every repo in the organization. Just added the core team to the repo, let me know if you can do it now.

**Comment by MikeRalphson** [comment]
Hmm, maybe we need admin not just write access to the repo in order to update the description and move issues?

**Comment by fmvilas** [comment]
You're now admin 😊

**Comment by MikeRalphson** [comment]
Thanks. github description and link updated. I can't seem to select any repositories to move open issues to. This article says admin rights are needed on both repos: https://help.github.com/en/articles/transferring-an-issue-to-another-repository
